CREATE TABLE stored_file (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             original_file_name VARCHAR(255),
                             stored_file_name VARCHAR(255),
                             device_name VARCHAR(255),
                             device_id BIGINT,
                             number_of_chunks INT,
                             file_relative_path VARCHAR(1024),
                             file_size BIGINT,
                             file_type VARCHAR(1024)
);

